[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.30"
solc = "/opt/homebrew/bin/solc"
optimizer = true
optimizer_runs = 200
via_ir = true

# Remappings - Foundry-installed libs take priority over node_modules
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@prb/math/=lib/prb-math/src/",
    "forge-std/=lib/forge-std/src/",
    # Legacy node_modules remappings (for reference)
    "polkamarkets-js/=node_modules/polkamarkets-js/",
]

# BNB Testnet RPC
[rpc_endpoints]
bnb_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"

# BSCScan API for contract verification
[etherscan]
bnb_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
